language: ruby
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
services:
  - redis-server
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - ondrej@bartas.cz
env:
  travis: 'yes'
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
